### ISSUE TITLE
crashes(ik its a opengl issue but i just switched from linux to windows so i need help fixing this error)

### ISSUE THREAD

**Issue by master7720** [Luna5ama/TrollHack#113]
Prism Launcher version: 7.1

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.224.2.21, 13.224.2.2, 13.224.2.107, 13.224.2.98]

session.minecraft.net resolves to:
    [13.107.246.70, 13.107.213.70]

textures.minecraft.net resolves to:
    [13.107.246.70, 13.107.213.70]

api.mojang.com resolves to:
    [13.107.246.70, 13.107.213.70]

Minecraft folder is:
C:/Users/notrocky/AppData/Roaming/PrismLauncher/instances/1.12.2/.minecraft

Java path is:
C:/Program Files/Java/jdk-1.8/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_371, using 64 (amd64) architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/instances/1.12.2/natives

Using system OpenAL.
Using system GLFW.

Libraries:
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-universal.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/notrocky/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔] TrollHack-1.2.0-nightly-6112293

Params:
  --username  --version 1.12.2 --gameDir C:/Users/notrocky/AppData/Roaming/PrismLauncher/instances/1.12.2/.minecraft --assetsDir C:/Users/notrocky/AppData/Roaming/PrismLauncher/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 6868

[01:05:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[01:05:18] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[01:05:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[01:05:18] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[01:05:18] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_371, running on Windows 11:amd64:10.0, installed at C:\Program Files\Java\jdk-1.8\jre
[01:05:18] [main/INFO] [FML]: Searching C:\Users\notrocky\AppData\Roaming\PrismLauncher\instances\1.12.2\.minecraft\mods for mods
[01:05:18] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in TrollHack-1.2.0-nightly-6112293.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[01:05:18] [main/WARN] [FML]: The coremod dev.luna5ama.loaderLoader.LegacyForgeLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[01:05:18] [main/WARN] [FML]: The coremod LegacyForgeLoader (dev.luna5ama.loaderLoader.LegacyForgeLoader) is not signed!
[01:05:18] [main/INFO] [dev.luna5ama.loaderLoader.core.Loader]: Loading mod into classloader
[01:05:18] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/notrocky/AppData/Roaming/PrismLauncher/instances/1.12.2/.minecraft/fastmc-loader/TrollHack-forge.jar Service=LaunchWrapper Env=CLIENT
[01:05:18] [main/WARN] [FML]: The coremod TrollHackCoreMod (dev.luna5ama.trollhack.TrollHackCoreMod) is not signed!
[01:05:18] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[01:05:18] [main/ERROR] [mixin]: Mixin config mixins.baritone.json does not specify "minVersion" property
[01:05:18] [main/INFO] [Troll Hack]: Troll Hack and Baritone mixins initialised.
[01:05:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:05:18] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[01:05:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[01:05:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:05:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:05:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:05:19] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[01:05:19] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[01:05:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:05:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:05:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:05:19] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[01:05:19] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@30814f43
[01:05:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[01:05:19] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[01:05:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[01:05:20] [main/WARN] [mixin]: Error loading class: Config (java.lang.ClassNotFoundException: The specified class 'Config' was not found)
[01:05:20] [main/WARN] [mixin]: @Mixin target net.minecraft.block.state.BlockStateContainer$StateImplementation is public in mixins.baritone.json:MixinStateImplementation and should be specified in value
[01:05:20] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[01:05:21] [Client thread/INFO] [minecraft/Minecraft]: Setting user: Master7720
[01:05:23] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[01:05:23] [Client thread/ERROR] [minecraft/Minecraft]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:625) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_371]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_371]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_371]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
[01:05:24] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
WARNING: coremods are present:
  TrollHackCoreMod (TrollHack-forge.jar)
  LegacyForgeLoader (TrollHack-1.2.0-nightly-6112293.jar)
Contact their authors BEFORE contacting forge
// This doesn't make any sense!
Time: 6/27/23 1:05 AM
Description: Initializing game
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_371, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 869368824 bytes (829 MB) / 1177550848 bytes (1123 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
TrollHackCoreMod (TrollHack-forge.jar)
  
LegacyForgeLoader (TrollHack-1.2.0-nightly-6112293.jar)
  
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
[01:05:24] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\notrocky\AppData\Roaming\PrismLauncher\instances\1.12.2\.minecraft\crash-reports\crash-2023-06-27_01.05.24-client.txt
Process exited with code -1.

**Comment by Luna5ama** [comment]
Try updating your graphics driver

**Comment by master7720** [comment]
> Try updating your graphics driver

i did all my drivers are updated

**Comment by master7720** [comment]
fixed it
