### ISSUE TITLE
crash log2

### ISSUE THREAD

**Issue by HPLNE** [Luna5ama/TrollHack#13]
WARNING: coremods are present:
  TrollHackCoreMode (TrollHack-0.0.1.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 4/10/22 3:19 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Troll Hack (trollhack)
Caused by: java.lang.ExceptionInInitializerError
	at cum.xiaro.trollhack.util.graphics.fastrender.tileentity.ChestRenderBuilder.<init>(ChestRenderBuilder.kt:27)
	at cum.xiaro.trollhack.module.modules.render.FastRender._init_$lambda-1(FastRender.kt:86)
	at cum.xiaro.trollhack.module.modules.render.FastRender$RenderEntry.<init>(FastRender.kt:195)
	at cum.xiaro.trollhack.module.modules.render.FastRender.<clinit>(FastRender.kt:308)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(Unknown Source)
	at sun.reflect.ReflectionFactory.newFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.getFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at cum.xiaro.trollhack.module.ModuleManager.load0(ModuleManager.kt:84)
	at cum.xiaro.trollhack.module.ModuleManager.load0(ModuleManager.kt:15)
	at cum.xiaro.trollhack.AsyncLoader$DefaultImpls.load(Loader.kt:49)
	at cum.xiaro.trollhack.module.ModuleManager.load(ModuleManager.kt:15)
	at cum.xiaro.trollhack.LoaderWrapper$loadAll$1.invokeSuspend(Loader.kt:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at cum.xiaro.trollhack.LoaderWrapper.loadAll(Loader.kt:31)
	at cum.xiaro.trollhack.TrollHackMod.init(TrollHackMod.kt:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Shader failed to link
	at cum.xiaro.trollhack.util.graphics.shaders.Shader.<init>(Shader.kt:28)
	at cum.xiaro.trollhack.util.graphics.shaders.DrawShader.<init>(DrawShader.kt:9)
	at cum.xiaro.trollhack.util.graphics.fastrender.tileentity.AbstractTileEntityRenderBuilder$Shader.<init>(AbstractTileEntityRenderBuilder.kt:116)
	at cum.xiaro.trollhack.util.graphics.fastrender.tileentity.ChestRenderBuilder$SmallChestRenderBuilder.<clinit>(ChestRenderBuilder.kt:230)
	... 66 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 165830680 bytes (158 MB) / 553648128 bytes (528 MB) up to 2791309312 bytes (2662 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx2662m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHI  | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHI  | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHI  | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | trollhack | 0.0.1        | TrollHack-0.0.1.jar           | None                                     |

	Loaded coremods (and transformers): 
TrollHackCoreMode (TrollHack-0.0.1.jar)

**Comment by HPLNE** [comment]
mod version is 0.0.1

**Comment by Luna5ama** [comment]
What GPU are you using?

**Comment by HPLNE** [comment]
> What GPU are you using?

openGL 3.3.0

**Comment by HPLNE** [comment]
[latest.log](https://github.com/Luna5ama/TrollHack/files/8499621/latest.log)

**Comment by HPLNE** [comment]
> 
[latest.log](https://github.com/Luna5ama/TrollHack/files/8499622/latest.log)

**Comment by HPLNE** [comment]
> 在 .minecraft/logs 中上传最新.log
[latest.log](https://github.com/Luna5ama/TrollHack/files/8499628/latest.log)

**Comment by TwoThreeTwo** [comment]
kami blue and trollhack dont work together (as far as I know, always had that issue), remove kami blue, stop using phobos 1.3.1 with trollhack and update your trollhack to the latest version :)

**Comment by HPLNE** [comment]
> kami blue和trollhack不能一起工作（据我所知，总是有这个问题），删除kami blue，停止使用phobos 1.3.1和trollhack，并将你的trollhack更新到最新版本:)
ok
