### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Emelmr** [Luna5ama/TrollHack#140]
Ultimmc MUltimc cracked crashed 
UltimMC version: 0.7.0-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [127.0.0.1]

session.minecraft.net resolves to:
    [13.107.246.73, 13.107.213.73]

textures.minecraft.net resolves to:
    [13.107.246.73, 13.107.213.73]

api.mojang.com resolves to:
    [13.107.246.73, 13.107.213.73]

Minecraft folder is:
C:/Users/tsuka/Desktop/UltimMC/instances/troll hack2/.minecraft

Java path is:
C:/Program Files/Amazon Corretto/jdk1.8.0_382/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_382, using 64-bit architecture, from Amazon.com Inc..

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/tsuka/Desktop/UltimMC/instances/troll hack2/natives

Libraries:
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-universal.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] 1.12.2-OptiFine_HD_U_G5.jar
  [✔️] TrollHack-1.3.1.jar

Params:
  --username <ACCESS TOKEN> --version 1.12.2 --gameDir C:/Users/tsuka/Desktop/UltimMC/instances/troll hack2/.minecraft --assetsDir C:/Users/tsuka/Desktop/UltimMC/assets --assetIndex 1.12 --uuid  --accessToken <ACCESS TOKEN> --userType Local --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-javaagent:C:/Users/tsuka/Desktop/UltimMC/injectors/authlib-injector-1.2.3.jar=http://localhost:52363, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 3600

[authlib-injector] [INFO] Logging file: C:\Users\tsuka\Desktop\UltimMC\instances\troll hack2\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.3
[authlib-injector] [INFO] Authentication server: http://localhost:52363
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

[20:44:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:44:21] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:44:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:44:21] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[20:44:21] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_382, running on Windows 10:amd64:10.0, installed at C:\Program Files\Amazon Corretto\jdk1.8.0_382\jre
[20:44:22] [main/INFO] [FML]: Searching C:\Users\tsuka\Desktop\UltimMC\instances\troll hack2\.minecraft\mods for mods
[20:44:22] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in TrollHack-1.3.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:44:26] [main/WARN] [FML]: The coremod dev.luna5ama.loaderLoader.LegacyForgeLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:44:26] [main/WARN] [FML]: The coremod LegacyForgeLoader (dev.luna5ama.loaderLoader.LegacyForgeLoader) is not signed!
[20:44:26] [main/INFO] [dev.luna5ama.loaderLoader.core.Loader]: Loading mod into classloader
[20:44:26] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/tsuka/Desktop/UltimMC/instances/troll%20hack2/.minecraft/fastmc-loader/TrollHack-forge.jar Service=LaunchWrapper Env=CLIENT
[20:44:26] [main/WARN] [FML]: The coremod TrollHackCoreMod (dev.luna5ama.trollhack.TrollHackCoreMod) is not signed!
[20:44:26] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[20:44:26] [main/ERROR] [mixin]: Mixin config mixins.baritone.json does not specify "minVersion" property
[20:44:26] [main/INFO] [Troll Hack]: Troll Hack and Baritone mixins initialised.
[20:44:26] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:44:26] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:44:26] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:44:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:44:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:44:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:44:33] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[20:44:33] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:44:33] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@37ce3644
[20:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:44:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:44:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:44:38] [main/WARN] [mixin]: Error loading class: Config (java.lang.ClassNotFoundException: The specified class 'Config' was not found)
[20:44:39] [main/WARN] [mixin]: @Mixin target net.minecraft.block.state.BlockStateContainer$StateImplementation is public in mixins.baritone.json:MixinStateImplementation and should be specified in value
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[20:44:39] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[authlib-injector] [INFO] Enable MC-52974 Workaround
[authlib-injector] [INFO] Httpd is running on port 52387
[authlib-injector] [INFO] Transformed [net.minecraft.client.entity.AbstractClientPlayer] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [MC-52974 Workaround]
[20:44:44] [Client thread/INFO] [minecraft/Minecraft]: Setting user: <ACCESS TOKEN>
[20:44:57] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[20:44:57] [Client thread/ERROR] [minecraft/Minecraft]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:797) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at net.minecraft.client.Minecraft.redirect$Redirect$createDisplay$INVOKE$Display$create$zzg000(Minecraft.java:3378) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:625) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[20:44:59] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TrollHackCoreMod (TrollHack-forge.jar)
  LegacyForgeLoader (TrollHack-1.3.1.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 9/23/23 8:44 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_382, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Amazon.com Inc.
	Memory: 442213168 bytes (421 MB) / 676331520 bytes (645 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
TrollHackCoreMod (TrollHack-forge.jar)
  
LegacyForgeLoader (TrollHack-1.3.1.jar)
  
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
[20:44:59] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\tsuka\Desktop\UltimMC\instances\troll hack2\.minecraft\crash-reports\crash-2023-09-23_20.44.59-client.txt
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

the loading screen maybe be animated and high quality resulting in crash or maybe jvm issues.If you can pls give me a version of trollhack with no loading screen just normal, Thanks for reading.

**Comment by Luna5ama** [comment]
Try updating your graphics driver.

**Comment by Emelmr** [comment]
thx
