### ISSUE TITLE
crashing游戏崩溃

### ISSUE THREAD

**Issue by neilhuang007** [Luna5ama/TrollHack#21]
here is the crash report
这是崩溃信息
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Troll Hack (trollhack)
Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Cancelled; job=JobImpl{Cancelled}@1a8675c7
Caused by: java.io.FileNotFoundException: /Users/huangsiying/Library/Application%20Support/minecraft/mods/TrollHack-0.0.2.jar (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at me.luna.trollhack.util.ClassUtils.findClassesInJar(ClassUtils.kt:67)
	at me.luna.trollhack.util.ClassUtils.findClasses(ClassUtils.kt:23)
	at me.luna.trollhack.AsyncLoader$Companion$classes$1.invokeSuspend(Loader.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by TwoThreeTwo** [comment]
provide full log

**Comment by neilhuang007** [comment]
ok

**Comment by master7720** [comment]
i cant read

**Comment by neilhuang007** [comment]
why

**Comment by pvc03** [comment]
Close FastRender

**Comment by neilhuang007** [comment]
what

**Comment by neilhuang007** [comment]
i can't even open it, how am i able to open fastrender

**Comment by underscore-gaimer-underscore** [comment]
unsupported gpu?

**Comment by TwoThreeTwo** [comment]
Why is Huang lying :(

**Comment by neilhuang007** [comment]
what?
