### ISSUE TITLE
what's the trouble

### ISSUE THREAD

**Issue by zjhim** [Luna5ama/TrollHack#25]
I tried many times,but it still won't start
log:
[19:32:48] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:32:48] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:32:48] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[19:32:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:32:48] [main/INFO]: Forge Mod Loader version 14.23.5.2859 for Minecraft 1.12.2 loading
[19:32:48] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_321, running on Windows 11:amd64:10.0, installed at E:\java8
[19:32:48] [main/INFO]: Searching F:\2b2t\no client-namida\.minecraft\mods for mods
[19:32:48] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in [R键整理]InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:32:48] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:32:48] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from TrollHack-0.0.3.jar
[19:32:48] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[19:32:48] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[19:32:48] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[19:32:48] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[19:32:48] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: F:\2b2t\no client-namida\.minecraft\libraries\optifine\OptiFine\1.12.2_HD_U_G6_pre1\OptiFine-1.12.2_HD_U_G6_pre1.jar
[19:32:48] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:32:48] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[19:32:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/F:/2b2t/no%20client-namida/.minecraft/mods/TrollHack-0.0.3.jar Service=LaunchWrapper Env=CLIENT
[19:32:48] [main/DEBUG]: Instantiating coremod class TrollHackCoreMod
[19:32:48] [main/TRACE]: coremod named TrollHackCoreMod is loading
[19:32:48] [main/DEBUG]: The coremod me.luna.trollhack.TrollHackCoreMod requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[19:32:48] [main/WARN]: The coremod TrollHackCoreMod (me.luna.trollhack.TrollHackCoreMod) is not signed!
[19:32:49] [main/INFO]: Compatibility level set to JAVA_8
[19:32:49] [main/ERROR]: Mixin config mixins.troll.core.json does not specify "minVersion" property
[19:32:49] [main/ERROR]: Mixin config mixins.troll.accessor.json does not specify "minVersion" property
[19:32:49] [main/ERROR]: Mixin config mixins.troll.patch.json does not specify "minVersion" property
[19:32:49] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[19:32:49] [main/INFO]: Troll Hack and Baritone mixins initialised.
[19:32:49] [main/DEBUG]: Enqueued coremod TrollHackCoreMod
[19:32:49] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:32:49] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:32:49] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:32:49] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:32:49] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[19:32:49] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[19:32:49] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[19:32:49] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[19:32:49] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[19:32:49] [main/DEBUG]: Injection complete
[19:32:49] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[19:32:49] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[19:32:51] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:32:51] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[19:32:51] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[19:32:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:32:51] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[19:32:51] [main/DEBUG]: Injection complete
[19:32:51] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[19:32:51] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[19:32:51] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[19:32:51] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[19:32:51] [main/ERROR]: Mixin config mixins.troll.core.json does not specify "minVersion" property
[19:32:51] [main/ERROR]: Mixin config mixins.troll.accessor.json does not specify "minVersion" property
[19:32:51] [main/ERROR]: Mixin config mixins.troll.patch.json does not specify "minVersion" property
[19:32:51] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@45f421c
[19:32:51] [main/DEBUG]: Injecting coremod TrollHackCoreMod \{me.luna.trollhack.TrollHackCoreMod\} class transformers
[19:32:51] [main/DEBUG]: Injection complete
[19:32:51] [main/DEBUG]: Running coremod plugin for TrollHackCoreMod \{me.luna.trollhack.TrollHackCoreMod\}
[19:32:51] [main/DEBUG]: Running coremod plugin TrollHackCoreMod
[19:32:51] [main/DEBUG]: Coremod plugin class TrollHackCoreMod run successfully
[19:32:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:32:51] [main/DEBUG]: Validating minecraft
[19:32:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:32:51] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:32:51] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:32:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:32:51] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:32:51] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[19:32:53] [main/WARN]: @Mixin target net.minecraft.block.state.BlockStateContainer$StateImplementation is public in mixins.baritone.json:MixinStateImplementation and should be specified in value
[19:32:53] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:32:54] [main/INFO]: InvTweaks: successfully transformed setFocused/func_146195_b
[19:32:54] [main/INFO]: [net.minecraft.client.main.Main:main:55]: Completely ignored arguments: [480, PCL2, ]
[19:32:54] [Client thread/INFO]: Setting user: PartnerQwQ
[19:32:59] [Client thread/INFO]: [OptiFine] *** Reflector Forge ***
[19:32:59] [Client thread/INFO]: [OptiFine] *** Reflector Vanilla ***
[19:32:59] [Client thread/WARN]: Skipping bad option: lastServer:
[19:32:59] [Client thread/INFO]: LWJGL Version: 2.9.4
[19:33:00] [Client thread/INFO]: [OptiFine] 
[19:33:00] [Client thread/INFO]: [OptiFine] OptiFine_1.12.2_HD_U_G6_pre1
[19:33:00] [Client thread/INFO]: [OptiFine] Build: 20210323-161358
[19:33:00] [Client thread/INFO]: [OptiFine] OS: Windows 11 (amd64) version 10.0
[19:33:00] [Client thread/INFO]: [OptiFine] Java: 1.8.0_321, Oracle Corporation
[19:33:00] [Client thread/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[19:33:00] [Client thread/INFO]: [OptiFine] LWJGL: 2.9.4
[19:33:00] [Client thread/INFO]: [OptiFine] OpenGL: NVIDIA GeForce GT 1030/PCIe/SSE2, version 4.6.0 NVIDIA 511.23, NVIDIA Corporation
[19:33:00] [Client thread/INFO]: [OptiFine] OpenGL Version: 4.6.0
[19:33:00] [Client thread/INFO]: [OptiFine] Maximum texture size: 32768x32768
[19:33:00] [VersionCheck/INFO]: [OptiFine] Checking for new version
[19:33:00] [Client thread/INFO]: [Shaders] OpenGL Version: 4.6.0 NVIDIA 511.23
[19:33:00] [Client thread/INFO]: [Shaders] Vendor:  NVIDIA Corporation
[19:33:00] [Client thread/INFO]: [Shaders] Renderer: NVIDIA GeForce GT 1030/PCIe/SSE2
[19:33:00] [Client thread/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  4.0 
[19:33:00] [Client thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[19:33:00] [Client thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[19:33:00] [Client thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
[19:33:00] [Client thread/INFO]: [Shaders] Load shaders configuration.
[19:33:00] [Client thread/INFO]: [Shaders] Save shaders configuration.
[19:33:00] [Client thread/INFO]: [Shaders] No shaderpack loaded.
[19:33:00] [Client thread/INFO]: [OptiFine] [Shaders] Delayed loading of block mappings after resources are loaded
[19:33:00] [Client thread/INFO]: [OptiFine] [Shaders] Delayed loading of item mappings after resources are loaded
[19:33:00] [Client thread/INFO]: [OptiFine] [Shaders] Delayed loading of entity mappings after resources are loaded
[19:33:01] [VersionCheck/INFO]: [OptiFine] Version found: G5
[19:33:02] [Client thread/INFO]: Forge Mod Loader has detected optifine OptiFine_1.12.2_HD_U_G6_pre1, enabling compatibility features
[19:33:02] [Client thread/INFO]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 279689792 bytes (266 MB) / 480247808 bytes (458 MB) up to 5798625280 bytes (5530 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx5529m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
TrollHackCoreMod (TrollHack-0.0.3.jar)
  
Inventory Tweaks Coremod ([R键整理]InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.23' Renderer: 'NVIDIA GeForce GT 1030/PCIe/SSE2'
[19:33:02] [Client thread/INFO]: MinecraftForge v14.23.5.2859 Initialized
[19:33:02] [Client thread/INFO]: Starts to replace vanilla recipe ingredients with ore ingredients.
[19:33:02] [Client thread/INFO]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[19:33:02] [Client thread/INFO]: Replaced 1227 ore ingredients
[19:33:03] [Client thread/INFO]: Searching F:\2b2t\no client-namida\.minecraft\mods for mods
[19:33:04] [Thread-3/INFO]: Using sync timing. 200 frames of Display.update took 126648600 nanos
[19:33:05] [Client thread/INFO]: Forge Mod Loader has identified 6 mods to load
[19:33:05] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, inventorytweaks, trollhack] at CLIENT
[19:33:05] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, inventorytweaks, trollhack] at SERVER
[19:33:05] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Troll Hack
[19:33:06] [Client thread/INFO]: Processing ObjectHolder annotations
[19:33:06] [Client thread/INFO]: Found 1168 ObjectHolder annotations
[19:33:06] [Client thread/INFO]: Identifying ItemStackHolder annotations
[19:33:06] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[19:33:06] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[19:33:06] [Forge Version Check/INFO]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[19:33:06] [Client thread/INFO]: Applying holder lookups
[19:33:06] [Client thread/INFO]: Holder lookups applied
[19:33:06] [Client thread/INFO]: Applying holder lookups
[19:33:06] [Client thread/INFO]: Holder lookups applied
[19:33:06] [Client thread/INFO]: Applying holder lookups
[19:33:06] [Client thread/INFO]: Holder lookups applied
[19:33:06] [Client thread/INFO]: Applying holder lookups
[19:33:06] [Client thread/INFO]: Holder lookups applied
[19:33:06] [Client thread/INFO]: Injecting itemstacks
[19:33:06] [Client thread/INFO]: Itemstack injection complete
[19:33:06] [Client thread/INFO]: [OptiFine] *** Reloading textures ***
[19:33:07] [Client thread/INFO]: [OptiFine] Resource packs: Default
[19:33:07] [Sound Library Loader/INFO]: Starting up SoundSystem...
[19:33:08] [Thread-8/INFO]: Initializing LWJGL OpenAL
[19:33:08] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[19:33:08] [Thread-8/INFO]: OpenAL initialized.
[19:33:08] [Sound Library Loader/INFO]: Sound engine started
[19:33:09] [DefaultDispatcher-worker-1/WARN]: Failed to check for translation updates
java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_321]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_321]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_321]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_321]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_321]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_321]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_321]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_321]
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_321]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_321]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_321]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_321]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_321]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_321]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_321]
	at java.net.URL.openStream(Unknown Source) ~[?:1.8.0_321]
	at kotlin.io.TextStreamsKt.readBytes(ReadWrite.kt:150) ~[TextStreamsKt.class:?]
	at me.luna.trollhack.translation.TranslationManager$checkUpdate$1.invokeSuspend(TranslationManager.kt:40) [TranslationManager$checkUpdate$1.class:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [BaseContinuationImpl.class:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [DispatchedTask.class:?]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) [LimitedDispatcher.class:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) [TaskImpl.class:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) [CoroutineScheduler.class:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) [CoroutineScheduler$Worker.class:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) [CoroutineScheduler$Worker.class:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) [CoroutineScheduler$Worker.class:?]
[19:33:09] [Forge Version Check/INFO]: [forge] Found status: UP_TO_DATE Target: null
[19:33:10] [Client thread/INFO]: [OptiFine] Mipmap levels: 4
[19:33:10] [Client thread/INFO]: [OptiFine] Multitexture: false
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_pane_white.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_white.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_pane_purple.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_purple.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_blue.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_pane_blue.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_brown.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_pane_brown.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_green.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_pane_green.properties
[19:33:10] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_pane_red.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_red.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_black.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_pane_black.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_orange.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_pane_orange.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_magenta.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_pane_magenta.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_light_blue.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_pane_light_blue.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_pane_yellow.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_yellow.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_lime.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_pane_lime.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pane_pink.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pink.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_gray.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_pane_gray.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_pane_silver.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_silver.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_cyan.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_pane_cyan.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/bookshelf.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glass.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glasspane.properties
[19:33:11] [Client thread/INFO]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/sandstone.properties
[19:33:11] [Client thread/INFO]: [OptiFine] Multipass connected textures: false
[19:33:11] [Client thread/INFO]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[19:33:13] [Client thread/INFO]: [OptiFine] Custom loader sprites: 3
[19:33:13] [Client thread/INFO]: [OptiFine] Sprite dependencies: 5
[19:33:13] [Client thread/INFO]: Created: 1024x512 textures-atlas
[19:33:13] [Client thread/INFO]: [OptiFine] Animated sprites: 22
[19:33:14] [Client thread/INFO]: Applying holder lookups
[19:33:14] [Client thread/INFO]: Holder lookups applied
[19:33:15] [Client thread/INFO]: Mod initialized
[19:33:15] [Client thread/INFO]: Initializing Troll Hack 0.0.3
[19:33:16] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TrollHackCoreMod (TrollHack-0.0.3.jar)
  Inventory Tweaks Coremod ([R键整理]InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 7/19/22 7:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Troll Hack (trollhack)
Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@5df215de
Caused by: java.io.FileNotFoundException: F:\2b2t\no%20client-namida\.minecraft\mods\TrollHack-0.0.3.jar (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at me.luna.trollhack.util.ClassUtils.findClassesInJar(ClassUtils.kt:67)
	at me.luna.trollhack.util.ClassUtils.findClasses(ClassUtils.kt:23)
	at me.luna.trollhack.AsyncLoader$Companion$classes$1.invokeSuspend(Loader.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 156665896 bytes (149 MB) / 556793856 bytes (531 MB) up to 5798625280 bytes (5530 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx5529m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G6_pre1 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                  | Source                         | Signature                                |
	|:----- |:--------------- |:------------------------ |:------------------------------ |:---------------------------------------- |
	| LCHI  | minecraft       | 1.12.2                   | minecraft.jar                  | None                                     |
	| LCHI  | mcp             | 9.42                     | minecraft.jar                  | None                                     |
	| LCHI  | FML             | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge           | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | inventorytweaks | 1.63+release.109.220f184 | [R键整理]InventoryTweaks-1.63.jar | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHE  | trollhack       | 0.0.3                    | TrollHack-0.0.3.jar            | None                                     |

	Loaded coremods (and transformers): 
TrollHackCoreMod (TrollHack-0.0.3.jar)
  
Inventory Tweaks Coremod ([R键整理]InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.23' Renderer: 'NVIDIA GeForce GT 1030/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 511.23
	OpenGlRenderer: NVIDIA GeForce GT 1030/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
[19:33:16] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# F:\2b2t\no client-namida\.minecraft\crash-reports\crash-2022-07-19_19.33.15-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Luna5ama** [comment]
Remove the space in the path for now. Will be fixed
