### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by toggledvktrr** [Luna5ama/TrollHack#26]
it wont start

**Comment by 213k** [comment]
if your pairing it with another client some wont work this happened to me with pyro but when i use it with 3arthh4ck it works perfectly

**Comment by toggledvktrr** [comment]
no i only started trollhack but it crash
i will send log

**Comment by toggledvktrr** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TrollHackCoreMod (TrollHack-0.0.3.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/22/22 10:07 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Troll Hack (trollhack)
Caused by: java.lang.ExceptionInInitializerError
	at me.luna.trollhack.gui.rgui.windows.TitledWindow.getDraggableHeight(TitledWindow.kt:18)
	at me.luna.trollhack.gui.rgui.windows.ColorPicker.updatePos(ColorPicker.kt:325)
	at me.luna.trollhack.gui.rgui.windows.ColorPicker.<clinit>(ColorPicker.kt:390)
	at me.luna.trollhack.gui.AbstractTrollGui.<init>(AbstractTrollGui.kt:91)
	at me.luna.trollhack.gui.hudgui.TrollHudGui.<init>(TrollHudGui.kt:24)
	at me.luna.trollhack.gui.hudgui.TrollHudGui.<clinit>(TrollHudGui.kt)
	at me.luna.trollhack.gui.GuiManager.register$TrollHack(GuiManager.kt:62)
	at me.luna.trollhack.gui.GuiManager.load0(GuiManager.kt:47)
	at me.luna.trollhack.gui.GuiManager.load0(GuiManager.kt:15)
	at me.luna.trollhack.AsyncLoader.load$suspendImpl(Loader.kt:49)
	at me.luna.trollhack.AsyncLoader.load(Loader.kt)
	at me.luna.trollhack.LoaderWrapper$loadAll$1.invokeSuspend(Loader.kt:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at me.luna.trollhack.LoaderWrapper.loadAll(Loader.kt:31)
	at me.luna.trollhack.TrollHackMod.init(TrollHackMod.kt:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL45.glCreateTextures(GL45.java:778)
	at me.luna.trollhack.util.graphics.font.GlyphTexture.<init>(GlyphTexture.kt:17)
	at me.luna.trollhack.util.graphics.font.glyph.FontGlyphs.<init>(FontGlyphs.kt:45)
	at me.luna.trollhack.util.graphics.font.renderer.AbstractFontRenderer.loadFont(AbstractFontRenderer.kt:56)
	at me.luna.trollhack.util.graphics.font.renderer.AbstractFontRenderer.<init>(AbstractFontRenderer.kt:37)
	at me.luna.trollhack.util.graphics.font.renderer.ExtendedFontRenderer.<init>(ExtendedFontRenderer.kt:6)
	at me.luna.trollhack.util.graphics.font.renderer.MainFontRenderer$DelegateFontRenderer.<init>(MainFontRenderer.kt:69)
	at me.luna.trollhack.util.graphics.font.renderer.MainFontRenderer.loadFont(MainFontRenderer.kt:38)
	at me.luna.trollhack.util.graphics.font.renderer.MainFontRenderer.<clinit>(MainFontRenderer.kt:18)
	... 63 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 407705704 bytes (388 MB) / 939524096 bytes (896 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_F5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHI  | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHI  | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHI  | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | trollhack | 0.0.3        | TrollHack-0.0.3.jar           | None                                     |

	Loaded coremods (and transformers): 
TrollHackCoreMod (TrollHack-0.0.3.jar)
  
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics 2000'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4459
	OpenGlRenderer: Intel(R) HD Graphics 2000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Luna5ama** [comment]
Get new gpu lmao
