### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Zane2b2t** [Luna5ama/TrollHack#29]
PLease fix ur client.

**Comment by Luna5ama** [comment]
Send log please

**Comment by Zane2b2t** [comment]
> Send log please

sec

**Comment by Zane2b2t** [comment]
# [latest.log](https://github.com/Luna5ama/TrollHack/files/9264047/latest.log)
[00:09:57] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:09:57] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:09:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[00:09:57] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[00:09:57] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 7:amd64:6.1, installed at C:\Users\tl\AppData\Roaming\.minecraft\runtime\jre-legacy\windows\jre-legacy
[00:09:57] [main/INFO]: Searching C:\Users\tl\AppData\Roaming\.minecraft\mods for mods
[00:09:57] [main/INFO]: Loading tweaker me.earth.earthhack.tweaker.EarthhackTweaker from 3arthh4ck-1.6.4-release.jar
[00:09:57] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine-OptiFine-1.12.2_HD_U_G5.jar
[00:09:57] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from TrollHack-0.0.3.jar
[00:09:57] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:09:57] [main/INFO]: Loading tweak class name me.earth.earthhack.tweaker.EarthhackTweaker
[00:09:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/tl/AppData/Roaming/.minecraft/mods/3arthh4ck-1.6.4-release.jar Service=LaunchWrapper Env=CLIENT
[00:09:58] [main/DEBUG]: Instantiating coremod class TrollHackCoreMod
[00:09:58] [main/TRACE]: coremod named TrollHackCoreMod is loading
[00:09:58] [main/DEBUG]: The coremod me.luna.trollhack.TrollHackCoreMod requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[00:09:58] [main/WARN]: The coremod TrollHackCoreMod (me.luna.trollhack.TrollHackCoreMod) is not signed!
[00:09:58] [main/INFO]: Compatibility level set to JAVA_8
[00:09:58] [main/ERROR]: Mixin config mixins.troll.core.json does not specify "minVersion" property
[00:09:58] [main/ERROR]: Mixin config mixins.troll.accessor.json does not specify "minVersion" property
[00:09:58] [main/ERROR]: Mixin config mixins.troll.patch.json does not specify "minVersion" property
[00:09:58] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[00:09:58] [main/INFO]: Troll Hack and Baritone mixins initialised.
[00:09:58] [main/DEBUG]: Enqueued coremod TrollHackCoreMod
[00:09:58] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[00:09:58] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[00:09:58] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:09:58] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:09:58] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:09:58] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[00:09:58] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[00:09:58] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[00:09:58] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[00:09:58] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\tl\AppData\Roaming\.minecraft\mods\OptiFine-OptiFine-1.12.2_HD_U_G5.jar
[00:09:58] [main/INFO]: Calling tweak class me.earth.earthhack.tweaker.EarthhackTweaker
[00:09:58] [main/ERROR]: Mixin config mixins.troll.core.json does not specify "minVersion" property
[00:09:58] [main/ERROR]: Mixin config mixins.troll.accessor.json does not specify "minVersion" property
[00:09:58] [main/ERROR]: Mixin config mixins.troll.patch.json does not specify "minVersion" property
[00:09:58] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@18ece7f4
[00:09:58] [main/DEBUG]: Injecting coremod TrollHackCoreMod \{me.luna.trollhack.TrollHackCoreMod\} class transformers
[00:09:58] [main/DEBUG]: Injection complete
[00:09:58] [main/DEBUG]: Running coremod plugin for TrollHackCoreMod \{me.luna.trollhack.TrollHackCoreMod\}
[00:09:58] [main/DEBUG]: Running coremod plugin TrollHackCoreMod
[00:09:58] [main/DEBUG]: Coremod plugin class TrollHackCoreMod run successfully
[00:09:58] [main/INFO]: 


[00:09:58] [main/INFO]: Initializing 3arthh4cks Core.
[00:09:58] [main/INFO]: Found Environment: SEARGE
[00:09:58] [main/INFO]: PluginManager: Scanning for PluginConfigs.
[00:09:58] [main/INFO]: Forge detected!
[00:09:58] [main/INFO]: Transformer instantiated.
[00:09:58] [main/INFO]: 


[00:09:58] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:09:58] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[00:09:58] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[00:09:58] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[00:09:58] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[00:09:58] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[00:09:58] [main/DEBUG]: Injection complete
[00:09:58] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[00:09:58] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[00:10:01] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[00:10:01] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[00:10:01] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[00:10:01] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:10:01] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[00:10:01] [main/DEBUG]: Injection complete
[00:10:01] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[00:10:01] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[00:10:01] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[00:10:01] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[00:10:01] [main/ERROR]: Mixin config mixins.troll.core.json does not specify "minVersion" property
[00:10:01] [main/ERROR]: Mixin config mixins.troll.accessor.json does not specify "minVersion" property
[00:10:01] [main/ERROR]: Mixin config mixins.troll.patch.json does not specify "minVersion" property
[00:10:01] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:10:01] [main/DEBUG]: Validating minecraft
[00:10:02] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:10:02] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[00:10:02] [main/WARN]: Tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker has already been visited -- skipping
[00:10:02] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:10:02] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[00:10:02] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[00:10:04] [main/WARN]: @Mixin target net.minecraft.block.state.BlockStateContainer$StateImplementation is public in mixins.baritone.json:MixinStateImplementation and should be specified in value
[00:10:05] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[00:10:06] [main/INFO]: Found 1 patch for: vg : net.minecraft.entity.Entity
[00:10:06] [main/INFO]: Done changing MixinPriority.
[00:10:08] [Client thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[00:10:08] [Client thread/INFO]: Setting user: PlzDontStealname
[00:10:09] [Client thread/INFO]: Found 1 patch for: fq : net.minecraft.util.math.Vec3i
[00:10:09] [Client thread/INFO]: Found 1 patch for: et : net.minecraft.util.math.BlockPos
[00:10:09] [Client thread/INFO]: Found 1 patch for: fa : net.minecraft.util.EnumFacing
[00:10:09] [Client thread/INFO]: Made EnumFacing.HORIZONTALS public!
[00:10:16] [Client thread/INFO]: [OptiFine] *** Reflector Forge ***
[00:10:17] [Client thread/INFO]: [OptiFine] *** Reflector Vanilla ***
[00:10:17] [Client thread/INFO]: Found 1 patch for: aec : net.minecraft.entity.player.InventoryPlayer
[00:10:17] [Client thread/INFO]: Made InventoryPlayer.currentItem volatile!
[00:10:17] [Client thread/INFO]: LWJGL Version: 2.9.4
[00:10:17] [Client thread/INFO]: [OptiFine] 
[00:10:17] [Client thread/INFO]: [OptiFine] OptiFine_1.12.2_HD_U_G5
[00:10:17] [Client thread/INFO]: [OptiFine] Build: 20210124-142939
[00:10:17] [Client thread/INFO]: [OptiFine] OS: Windows 7 (amd64) version 6.1
[00:10:17] [Client thread/INFO]: [OptiFine] Java: 1.8.0_51, Oracle Corporation
[00:10:17] [Client thread/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[00:10:17] [Client thread/INFO]: [OptiFine] LWJGL: 2.9.4
[00:10:17] [Client thread/INFO]: [OptiFine] OpenGL: Intel(R) HD Graphics 3000, version 3.1.0 - Build 9.17.10.4229, Intel
[00:10:17] [Client thread/INFO]: [OptiFine] OpenGL Version: 3.1.0
[00:10:17] [Client thread/INFO]: [OptiFine] OpenGL Fancy fog: Not available (GL_NV_fog_distance)
[00:10:17] [Client thread/INFO]: [OptiFine] Maximum texture size: 8192x8192
[00:10:17] [VersionCheck/INFO]: [OptiFine] Checking for new version
[00:10:17] [Client thread/INFO]: [Shaders] OpenGL Version: 3.1.0 - Build 9.17.10.4229
[00:10:17] [Client thread/INFO]: [Shaders] Vendor:  Intel
[00:10:17] [Client thread/INFO]: [Shaders] Renderer: Intel(R) HD Graphics 3000
[00:10:17] [Client thread/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  -  - 
[00:10:17] [Client thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[00:10:17] [Client thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[00:10:17] [Client thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[00:10:17] [Client thread/INFO]: [Shaders] Load shaders configuration.
[00:10:17] [Client thread/INFO]: [Shaders] Save shaders configuration.
[00:10:17] [Client thread/INFO]: [Shaders] No shaderpack loaded.
[00:10:18] [Client thread/INFO]: [OptiFine] [Shaders] Delayed loading of block mappings after resources are loaded
[00:10:18] [Client thread/INFO]: [OptiFine] [Shaders] Delayed loading of item mappings after resources are loaded
[00:10:18] [Client thread/INFO]: [OptiFine] [Shaders] Delayed loading of entity mappings after resources are loaded
[00:10:18] [VersionCheck/INFO]: [OptiFine] Version found: G5
[00:10:19] [Client thread/INFO]: Forge Mod Loader has detected optifine OptiFine_1.12.2_HD_U_G5, enabling compatibility features
[00:10:20] [Client thread/INFO]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 65295528 bytes (62 MB) / 267460608 bytes (255 MB) up to 3091988480 bytes (2948 MB)
	JVM Flags: 2 total; -Xmx2982M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
TrollHackCoreMod (TrollHack-0.0.3.jar)
  
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
[00:10:20] [3arthh4ck-Thread-0/INFO]: Caching Sphere...
[00:10:20] [Client thread/INFO]: MinecraftForge v14.23.5.2860 Initialized
[00:10:20] [Client thread/INFO]: Starts to replace vanilla recipe ingredients with ore ingredients.
[00:10:20] [Client thread/INFO]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[00:10:20] [Client thread/INFO]: Replaced 1227 ore ingredients
[00:10:21] [Client thread/INFO]: Searching C:\Users\tl\AppData\Roaming\.minecraft\mods for mods
[00:10:23] [Thread-3/INFO]: Using sync timing. 200 frames of Display.update took 382211129 nanos
[00:10:28] [Client thread/INFO]: Forge Mod Loader has identified 5 mods to load
[00:10:28] [Client thread/INFO]: FML has found a non-mod file 3arthh4ck-1.6.4-release.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[00:10:29] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, trollhack] at CLIENT
[00:10:29] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, trollhack] at SERVER
[00:10:31] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Troll Hack, Better PCvA
[00:10:31] [Client thread/INFO]: Processing ObjectHolder annotations
[00:10:31] [Client thread/INFO]: Found 1168 ObjectHolder annotations
[00:10:31] [Client thread/INFO]: Identifying ItemStackHolder annotations
[00:10:31] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[00:10:32] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[00:10:32] [Forge Version Check/INFO]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[00:10:33] [Client thread/INFO]: Applying holder lookups
[00:10:33] [Client thread/INFO]: Holder lookups applied
[00:10:33] [Client thread/INFO]: Applying holder lookups
[00:10:33] [Client thread/INFO]: Holder lookups applied
[00:10:33] [Client thread/INFO]: Applying holder lookups
[00:10:33] [Client thread/INFO]: Holder lookups applied
[00:10:33] [Client thread/INFO]: Applying holder lookups
[00:10:33] [Client thread/INFO]: Holder lookups applied
[00:10:33] [Client thread/INFO]: Injecting itemstacks
[00:10:33] [Client thread/INFO]: Itemstack injection complete
[00:10:33] [Client thread/INFO]: [OptiFine] *** Reloading textures ***
[00:10:33] [Client thread/INFO]: [OptiFine] Resource packs: Better PCvA
[00:10:37] [Sound Library Loader/INFO]: Starting up SoundSystem...
[00:10:37] [Thread-8/INFO]: Initializing LWJGL OpenAL
[00:10:37] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[00:10:38] [Client thread/INFO]: [OptiFine] Loading mcpatcher/font/ascii.properties
[00:10:38] [Client thread/INFO]: [OptiFine] Loading mcpatcher/font/ascii_sga.properties
[00:10:38] [Thread-8/INFO]: OpenAL initialized.
[00:10:38] [Sound Library Loader/INFO]: Sound engine started
[00:10:42] [3arthh4ck-Thread-0/INFO]: Cached sphere in 22546ms.
[00:10:44] [Troll Hack Main/INFO]: 1868 classes found, took 10925ms
[00:10:44] [Troll Hack Main/INFO]: 166 modules found, took 30ms
[00:10:44] [Troll Hack Main/INFO]: 22 commands found, took 5ms
[00:10:44] [Troll Hack Main/INFO]: 17 managers found, took 5ms
[00:10:44] [Troll Hack Main/INFO]: 27 hud elements found, took 5ms
[00:10:49] [Client thread/INFO]: Found 1 patch for: bsa : net.minecraft.client.multiplayer.PlayerControllerMP
[00:10:49] [Client thread/INFO]: Made PlayerControllerMP.currentPlayerItem volatile!
[00:10:50] [Client thread/INFO]: [OptiFine] Mipmap levels: 4
[00:10:50] [Client thread/INFO]: [OptiFine] Multitexture: false
[00:10:50] [Client thread/INFO]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[00:10:52] [Client thread/INFO]: [OptiFine] Custom loader sprites: 3
[00:10:52] [Client thread/INFO]: [OptiFine] Sprite dependencies: 5
[00:10:52] [Client thread/INFO]: Created: 512x512 textures-atlas
[00:10:52] [Client thread/INFO]: [OptiFine] Animated sprites: 22
[00:10:55] [Client thread/INFO]: Applying holder lookups
[00:10:55] [Client thread/INFO]: Holder lookups applied
[00:10:55] [Client thread/INFO]: Initializing Troll Hack 0.0.3
[00:10:56] [Client thread/INFO]: 166 modules loaded, took 1307ms
[00:10:56] [Client thread/INFO]: 22 commands loaded, took 57ms
[00:10:57] [Client thread/INFO]: 17 managers loaded, took 69ms
[00:10:58] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TrollHackCoreMod (TrollHack-0.0.3.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 8/5/22 12:10 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Troll Hack (trollhack)
Caused by: java.lang.ExceptionInInitializerError
	at me.luna.trollhack.gui.rgui.windows.TitledWindow.getDraggableHeight(TitledWindow.kt:18)
	at me.luna.trollhack.gui.rgui.windows.ColorPicker.updatePos(ColorPicker.kt:325)
	at me.luna.trollhack.gui.rgui.windows.ColorPicker.<clinit>(ColorPicker.kt:390)
	at me.luna.trollhack.gui.AbstractTrollGui.<init>(AbstractTrollGui.kt:91)
	at me.luna.trollhack.gui.hudgui.TrollHudGui.<init>(TrollHudGui.kt:24)
	at me.luna.trollhack.gui.hudgui.TrollHudGui.<clinit>(TrollHudGui.kt)
	at me.luna.trollhack.gui.GuiManager.register$TrollHack(GuiManager.kt:62)
	at me.luna.trollhack.gui.GuiManager.load0(GuiManager.kt:47)
	at me.luna.trollhack.gui.GuiManager.load0(GuiManager.kt:15)
	at me.luna.trollhack.AsyncLoader.load$suspendImpl(Loader.kt:49)
	at me.luna.trollhack.AsyncLoader.load(Loader.kt)
	at me.luna.trollhack.LoaderWrapper$loadAll$1.invokeSuspend(Loader.kt:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at me.luna.trollhack.LoaderWrapper.loadAll(Loader.kt:31)
	at me.luna.trollhack.TrollHackMod.init(TrollHackMod.kt:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL45.glCreateTextures(GL45.java:778)
	at me.luna.trollhack.util.graphics.font.GlyphTexture.<init>(GlyphTexture.kt:17)
	at me.luna.trollhack.util.graphics.font.glyph.FontGlyphs.<init>(FontGlyphs.kt:45)
	at me.luna.trollhack.util.graphics.font.renderer.AbstractFontRenderer.loadFont(AbstractFontRenderer.kt:56)
	at me.luna.trollhack.util.graphics.font.renderer.AbstractFontRenderer.<init>(AbstractFontRenderer.kt:37)
	at me.luna.trollhack.util.graphics.font.renderer.ExtendedFontRenderer.<init>(ExtendedFontRenderer.kt:6)
	at me.luna.trollhack.util.graphics.font.renderer.MainFontRenderer$DelegateFontRenderer.<init>(MainFontRenderer.kt:69)
	at me.luna.trollhack.util.graphics.font.renderer.MainFontRenderer.loadFont(MainFontRenderer.kt:38)
	at me.luna.trollhack.util.graphics.font.renderer.MainFontRenderer.<clinit>(MainFontRenderer.kt:18)
	... 63 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 193059808 bytes (184 MB) / 853352448 bytes (813 MB) up to 3091988480 bytes (2948 MB)
	JVM Flags: 2 total; -Xmx2982M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHI  | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHI  | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHI  | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | trollhack | 0.0.3        | TrollHack-0.0.3.jar           | None                                     |

	Loaded coremods (and transformers): 
TrollHackCoreMod (TrollHack-0.0.3.jar)
  
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 1
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4229
	OpenGlRenderer: Intel(R) HD Graphics 3000
	OpenGlVendor: Intel
	CpuCount: 4
[00:10:58] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\tl\AppData\Roaming\.minecraft\crash-reports\crash-2022-08-05_00.10.57-client.txt


Using the client just by itself is just not good

**Comment by Luna5ama** [comment]
`GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'`

Your GPU is unsupported because it is too old. Get a new GPU.

**Comment by Zane2b2t** [comment]
> `GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'`
> 
> Your GPU is unsupported because it is too old. Get a new GPU.

I tried with my brother's pc and still doesnt work
Its gtx 780ti

**Comment by Luna5ama** [comment]
> > `GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'`
> > 
> > Your GPU is unsupported because it is too old. Get a new GPU.
> 
> I tried with my brother's pc and still doesnt work
> Its gtx 780ti

Try updating driver
