### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Staaarley** [Luna5ama/TrollHack#86]
[00:29:34] [Client thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.j
	at baritone.j.a(Unknown Source) ~[j.class:1.2.14]
	at baritone.j.onTick(Unknown Source) ~[j.class:1.2.14]
	at baritone.cf.a(Unknown Source) ~[cf.class:1.2.14]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:1.8.0_351]
	at baritone.cf.onTick(Unknown Source) ~[cf.class:1.2.14]
	at net.minecraft.client.Minecraft.handler$runTick$zdp000(Minecraft.java) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[00:29:34] [pool-3-thread-7/INFO] [STDOUT]: [baritone.m:a:-1]: Saved region successfully
[00:29:34] [pool-3-thread-7/INFO] [STDOUT]: [baritone.n:save:-1]: World save took 32ms
[00:29:35] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TrollHackCoreMod (TrollHack-forge.jar)
  LegacyForgeLoader (TrollHack-0.0.7.jar)
  XaeroWorldMapPlugin (WorldMap-v1.28.3-for-Forge-1.12.2.jar)
  XaeroMinimapPlugin (Minimap-v22.16.2-for-Forge-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/9/23 12:29 AM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.j
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zdp000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zdp000(Minecraft.java)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['CodyPro'/735885, l='MpServer', x=49353.23, y=18.00, z=1709.96]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 114499 game time, 1622026514 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 8 total; [EntityCreeper['Крипер'/735887, l='MpServer', x=49353.27, y=8.00, z=1699.47], EntityPlayerSP['CodyPro'/735885, l='MpServer', x=49353.23, y=18.00, z=1709.96], EntitySpider['Паук'/735891, l='MpServer', x=49333.39, y=6.00, z=1703.20], EntityCreeper['Крипер'/735890, l='MpServer', x=49340.30, y=11.00, z=1700.21], EntitySpider['Паук'/735889, l='MpServer', x=49350.22, y=7.00, z=1703.10], EntitySpider['Паук'/735888, l='MpServer', x=49352.13, y=8.00, z=1696.79], EntityCreeper['Крипер'/735893, l='MpServer', x=49352.48, y=11.00, z=1691.69], EntitySpider['Паук'/735892, l='MpServer', x=49338.70, y=16.00, z=1702.70]]
	Retry entities: 0 total; []
	Server brand: YOMUM
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_351, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5693552456 bytes (5429 MB) / 6134169600 bytes (5850 MB) up to 6134169600 bytes (5850 MB)
	JVM Flags: 4 total; -Xverify:none -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6000m -Xmx6000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version      | Source                                  | Signature                                |
	|:------ |:------------------ |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp                | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2859-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2859 | forge-1.12.2-14.23.5.2859-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core  | 1.12.2-1.0   | minecraft.jar                           | None                                     |
	| LCHIJA | xaeroworldmap_core | 1.12.2-1.0   | minecraft.jar                           | None                                     |
	| LCHIJA | xaerominimap       | 22.16.2      | Minimap-v22.16.2-for-Forge-1.12.2.jar   | None                                     |
	| LCHIJA | trollhack          | 0.0.7        | TrollHack-0.0.7.jar                     | None                                     |
	| LCHIJA | xaeroworldmap      | 1.28.3       | WorldMap-v1.28.3-for-Forge-1.12.2.jar   | None                                     |

	Loaded coremods (and transformers): 
TrollHackCoreMod (TrollHack-forge.jar)
  
LegacyForgeLoader (TrollHack-0.0.7.jar)
  
XaeroWorldMapPlugin (WorldMap-v1.28.3-for-Forge-1.12.2.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
XaeroMinimapPlugin (Minimap-v22.16.2-for-Forge-1.12.2.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 528.24' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 528.24, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 528.24
	OpenGlRenderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
[00:29:35] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# D:\РАБ СТОЛ САМЫЙ ПОСЛЕДНИЙ\MultiMC\instances\1.12.22\.minecraft\crash-reports\crash-2023-02-09_00.29.34-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Процесс завершён с кодом -1 (0xffffffffffffffff).
Пожалуйста, обратите внимание, что обычно ни кода выхода, ни его описания недостаточно для диагностики проблем!
Всегда загружать весь журнал целиком, а не только код выхода.

**Comment by Staaarley** [comment]
[latest.log](https://github.com/Luna5ama/TrollHack/files/10690102/latest.log)

**Comment by Staaarley** [comment]
[crash-2023-02-09_00.29.34-client.txt](https://github.com/Luna5ama/TrollHack/files/10690108/crash-2023-02-09_00.29.34-client.txt)

**Comment by Luna5ama** [comment]
Remove `-Xverify:none`
