### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by master7720** [Luna5ama/TrollHack#9]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TrollHackCoreMod (TrollHack-0.0.2-Release.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 3/12/22 1:59 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.k
	at baritone.k.a(Unknown Source)
	at baritone.k.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at baritone.cf$$Lambda$933/965937772.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zdn000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.k.a(Unknown Source)
	at baritone.k.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at baritone.cf$$Lambda$933/965937772.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zdn000(Minecraft.java)

-- Affected level --
Details:
	Level name: MpServer
	All players: 9 total; [EntityPlayerSP['Jaraxxus_'/25478636, l='MpServer', x=11.60, y=123.06, z=-1.84], EntityOtherPlayerMP['jacobhanson91'/25474022, l='MpServer', x=0.00, y=122.00, z=7.90], EntityOtherPlayerMP['Primooctopus33'/25476991, l='MpServer', x=10.69, y=3.00, z=10.30], EntityOtherPlayerMP['CoolYO_360'/25475198, l='MpServer', x=8.59, y=4.00, z=11.70], EntityOtherPlayerMP['PollosxD'/25476686, l='MpServer', x=5.27, y=4.22, z=4.71], EntityOtherPlayerMP['bopis'/25474023, l='MpServer', x=18.89, y=121.00, z=1.73], EntityOtherPlayerMP['Chachoox'/25478255, l='MpServer', x=-29.58, y=133.12, z=1.62], EntityOtherPlayerMP['Luris20'/25477157, l='MpServer', x=5.36, y=4.00, z=11.30], EntityOtherPlayerMP['Zaceuuu'/25476912, l='MpServer', x=-0.32, y=122.00, z=-0.93]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,122,0), Chunk: (at 0,7,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 148818 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntityPlayerSP['Jaraxxus_'/25478636, l='MpServer', x=11.60, y=123.06, z=-1.84], EntitySnowman['Snow Golem'/1, l='MpServer', x=-17.50, y=122.00, z=-24.50], EntityOtherPlayerMP['ExtraTab'/25476995, l='MpServer', x=6.70, y=5.00, z=9.38], EntitySnowman['Snow Golem'/2, l='MpServer', x=-26.50, y=121.00, z=6.50], EntityOtherPlayerMP['jacobhanson91'/25474022, l='MpServer', x=0.00, y=122.00, z=7.90], EntityOtherPlayerMP['Primooctopus33'/25476991, l='MpServer', x=10.69, y=3.00, z=10.30], EntitySnowman['Snow Golem'/4, l='MpServer', x=-3.50, y=121.00, z=29.50], EntityOtherPlayerMP['CoolYO_360'/25475198, l='MpServer', x=8.59, y=4.00, z=11.70], EntitySnowman['Snow Golem'/5, l='MpServer', x=20.50, y=121.00, z=-17.50], EntitySnowman['Snow Golem'/6, l='MpServer', x=21.50, y=121.00, z=-9.50], EntityOtherPlayerMP['PollosxD'/25476686, l='MpServer', x=5.27, y=4.22, z=4.71], EntitySnowman['Snow Golem'/7, l='MpServer', x=17.50, y=121.00, z=23.50], EntityOtherPlayerMP['bopis'/25474023, l='MpServer', x=18.89, y=121.00, z=1.73], EntityOtherPlayerMP['Chachoox'/25478255, l='MpServer', x=-29.58, y=133.12, z=1.62], EntityOtherPlayerMP['Luris20'/25477157, l='MpServer', x=5.36, y=4.00, z=11.30], EntityOtherPlayerMP['Zaceuuu'/25476912, l='MpServer', x=-0.32, y=122.00, z=-0.93], EntityOtherPlayerMP['Luris20'/25477157, l='MpServer', x=5.36, y=4.00, z=11.30], EntityOtherPlayerMP['Zaceuuu'/25476912, l='MpServer', x=-0.32, y=122.00, z=-0.93], EntityOtherPlayerMP['PollosxD'/25476686, l='MpServer', x=5.27, y=4.22, z=4.71], EntityEnderCrystal['entity.EnderCrystal.name'/25479126, l='MpServer', x=10.50, y=4.00, z=9.50], EntityEnderCrystal['entity.EnderCrystal.name'/25479127, l='MpServer', x=5.50, y=5.00, z=9.50], EntityOtherPlayerMP['jacobhanson91'/25474022, l='MpServer', x=0.00, y=122.00, z=7.90], EntityOtherPlayerMP['bopis'/25474023, l='MpServer', x=18.89, y=121.00, z=1.73], EntityOtherPlayerMP['Chachoox'/25478255, l='MpServer', x=-29.58, y=133.12, z=1.62], EntityEnderCrystal['entity.EnderCrystal.name'/25436913, l='MpServer', x=-3.50, y=4.00, z=-43.50], EntityOtherPlayerMP['CoolYO_360'/25475198, l='MpServer', x=8.59, y=4.00, z=11.70], EntityOtherPlayerMP['Primooctopus33'/25476991, l='MpServer', x=10.69, y=3.00, z=10.30]]
	Retry entities: 0 total; []
	Server brand: Crystal (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Luna5ama** [comment]
Remove `-noverify` from your launch VMoptions

**Comment by thousandstarr** [comment]
same, also crashes for me HEEEEEEEEEEEEEEEELPPPPPPPPPPPPPPPPPPPEEEEEEEEEEEEEE

**Comment by TwoThreeTwo** [comment]
> same, also crashes for me HEEEEEEEEEEEEEEEELPPPPPPPPPPPPPPPPPPPEEEEEEEEEEEEEE
Remove -noverify from your launch VMoptions
Learn to read.

**Comment by master7720** [comment]
> same, also crashes for me HEEEEEEEEEEEEEEEELPPPPPPPPPPPPPPPPPPPEEEEEEEEEEEEEE

or turn off all the settings for the combat module
